version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myserv:latest
    container_name: myserv-app-container
    ports:
      - "8181:8181"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: myserv-mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: