name: CI Pipeline for Dockerized Go App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag Docker image
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run containers
        run: |
          docker-compose -f docker-compose.yml up -d
          sleep 10
          
      - name: Run tests inside the container
        run: |
          docker exec myserv-app-container go test ./tests -v

      - name: Stop and clean up
        run: docker-compose -f docker-compose.yml down